### ISSUE TITLE
[front] 전화번호 입력받을 때, 하이픈 양식 지정

### ISSUE THREAD

**Issue by inthewalter** [HGU-CRA/i-ticket#13]
전화번호 입력받을 때, 하이픈이 자동으로 생성이 되거나 칸을 나눠야할 듯~

```
    <div class="info-phone">
      <label class="info-phone-label">phone</label>
      <!-- TODO: 하이픈이 자동으로 입력되거나 양식을 정해주는 게 좋을 듯 by walter -->
      <input class="info-phone-input" type="text" placeholder="010-1234-5678" [(ngModel)]="phoneNumber">
    </div>
```

**Comment by EunsungKoh** [comment]
현재 validator내에서는
//validation example
//010-xxxx-xxxx
//(011|011|016|017|018|019)-xxxx-xxx
//(011|011|016|017|018|019)-xxx-xxx

방식으로 하고있는데
이걸 명시해주는게 더 깔끔하려나?
@inthewalter

**Comment by inthewalter** [comment]
@EunsungKoh 그 사람들이 하이픈을 직접 입력하지 않게? 자동으로 삽입이 된다던지, 틀이 정해져있다던지>??

**Comment by EunsungKoh** [comment]
차라리 -를 빼고 입력하도록 하는건 어때?

01012345678
이런식으로
@inthewalter @ykss

**Comment by inthewalter** [comment]
@EunsungKoh 그래두 될 거 같고, 다만 그렇게 할 경우
01072660275 라고 쓰는 사람도 있고
010-7266-0275 라고 쓰는 사람도 있고..
010 7266 0275 라고 쓰는 사람 등등..이 있을 거 같으으응ㅁ
@ykss 이 아저씬 보지도 않네 ㅜㅜ

**Comment by ykss** [comment]
-없게 해서 특수문자들어가면 안되는걸로 valid 조건을 해도될거같음

**Comment by EunsungKoh** [comment]
해결!
