### ISSUE TITLE
[back] seller register 과정에서 내용 없이 게시물을 작성할 경우

### ISSUE THREAD

**Issue by EunsungKoh** [HGU-CRA/i-ticket#22]
```  
  //판매등록 시 파이어베이스로 데이터 넘김
  updateConcert() {
    //TODO: 아무 내용없이 글을 작성할 경우에 오류 발생
 ```

내용이 길어서 메소드 이름만 남기는데, 
게시물을 작성할때 내용이 없이는 작성 못하게 막아야 할듯! 
이걸 해결하다보면 #12  도 같이 해결되지 않을까?

**Comment by ykss** [comment]
일단 편법같은 느낌으로 html단에서 입력값이 없으면 판매등록 버튼을 disabled되게 해놨음.
validator 쓰려면 코드 한번 엎어야할듯
